// Validation constants for MCP write endpoints
export const VALIDATION_CONSTANTS = {
	MAX_TITLE_LENGTH: 200,
	MAX_SUBJECT_LENGTH: 100,
	LEECH_THRESHOLD: 3,
	MIN_DIFFICULTY: 1,
	MAX_DIFFICULTY: 10,
	MIN_QUALITY_SCORE: 0,
	MAX_QUALITY_SCORE: 5,
	DEFAULT_ESTIMATED_DURATION: 15,
} as const;
